### ISSUE TITLE
To-Do List to publish the new Freeman font

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/Freeman#12]
This would be the To-Do list for Freeman's onboarding process

- [x] Rename the repository or create a new one named Freeman
- [x] Update the font info with the new repository (copyright string) + designer and manufacturer urls
- [x] Update the Readme info for the new font
- [x] Update AUTHORS and CONTRIBUTORS files
- [x] Create a new description for the font
- [x] Inspect the [Mastering Issue](https://github.com/rfuenzalida/FrancoisOne-Font/issues/10) and solve what is suggested there to review
- [x] Inspect the issue [FB Warns reported](https://github.com/rfuenzalida/FrancoisOne-Font/issues/11) for Freeman and solve everything that should be addressed. Particularly: 
- "WARN: Check font contains no unreachable glyphs" --> E.g. `.orig` and `.sups` would need a feature to reach them
- "WARN: Check if each glyph has the recommended amount of contours" --> Often useful to detect exporting issues.

**Comment by rfuenzalida** [comment]
Issues should be fixed.
