### ISSUE TITLE
To-Do list for publishing

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/Freeman#16]
Hi @rfuenzalida, this would be the To-Do list in preparation for Freeman's publishing, summarizing what we discussed at our last meeting about the project.

**Research and understand the files related to the Francois/Freeman projects** to choose the best characteristics of each one as a base to start the development of the new version of the font.

- [ ] Go back in history to reinstate the changes introduced by the Summer of Type and Aoife Mooney (that is before the metrics and other added changes). Probably at commit `d0ce59f`
   Aoife Mooney [`FrancoisOne.glyphs` ](https://github.com/aoifemooney/francoisoneFont/blob/master/sources/FrancoisOne.glyphs) source file included the following key changes: 
    - Junctions transition and arches change of speed
    - Most of the strokes endings go from sloped to flat (both in lowercase and Uppercase, although `A` and `M` go the other way)
    - `R` lobe proportion changed. `K` upper arm turned to slope instead of flat. `e` eye + aperture proportion 
    - Tighter spacing 
    ![Aoife-Mooney-key-features](https://github.com/rfuenzalida/Freeman/assets/48698976/d73c26f4-89fd-4552-9ff2-90654ea012a8)
- [ ] Introduce the changes made by Jacques that could benefit the project, e.g. `Sterling`

**Mastering stage**
 
- [ ] Give the font and overall revision. Spacing, kerning, marks like the list in #10 
- [ ] Add & improve Sub-Saharan African (SSA) language support.

**Production stage**
- [ ] Include Aoife Mooney in the Authors and Contributors list. We should double-check with @davelab6 how to acknowledge the Summer of Type work.
- [ ] Prepare the font to be published into GF. Solving any reported fail or fix required like the ones reported in #11.

**Comment by rfuenzalida** [comment]
Hi @vv-monsalve attached I'm sending the diffenator proofs of the current update for the font

**Comment by rfuenzalida** [comment]
@vv-monsalve here are the diffenator proofs so you can check the changes for Freeman based on the to do list.

![diffbrowsers_glyphs-macOS-14 0-x86_64-i386-64bit_chrome_118 0 5993 117](https://github.com/rfuenzalida/Freeman/assets/8063083/a2374940-5e0e-4e35-b981-a794b7de82b8)
![diffbrowsers_text-macOS-14 0-x86_64-i386-64bit_chrome_118 0 5993 117](https://github.com/rfuenzalida/Freeman/assets/8063083/a9d4c60c-2a0b-4ee9-9f40-b13a477002d3)
![diffbrowsers_waterfall-macOS-14 0-x86_64-i386-64bit_chrome_118 0 5993 117](https://github.com/rfuenzalida/Freeman/assets/8063083/0e6c9a1e-fd73-4b47-9a66-6de541e20f04)
